### ISSUE TITLE
Domain Error with Thyrosim file: figures-RTF-4.24.2024.ipynb

### ISSUE THREAD

**Issue by ksreid9** [biona001/Thyrosim.jl#1]
I have been receiving a domain error when I run this file. Specifically in the code under the "Female patients: normal, skinny, obese simulations" and "Male patient simulations: normal, skinny, obese" headers. I am not sure if there is an issue with the equations used but negative numbers should not be outputted. Attached is a screenshot of the error message I am receiving.

Part of the error message: 
"DomainError with -3.864940990896759e-7:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar."

<img width="1125" alt="Screenshot 2024-11-07 at 6 54 11 PM" src="https://github.com/user-attachments/assets/475d8e65-4912-4ed5-9f89-2d5fdbc23dd2">

Thanks!

**Comment by biona001** [comment]
@ksreid9 Thanks for reporting a bug, but in order to debug it, I need to be able to reproduce the bug. Can you give me a minimal reproducible example (that is, copy and paste the code you executed here)?

**Comment by ksreid9** [comment]
Here is the code up to the issues. I also attached the .ipynb file that you
gave me that shows all the errors when I run it. I did not make any changes
to the original code so I'm not sure why it ran fine for you but not me.


using Revise
using Thyrosim
using Plots
using CSV
using DataFrames
gr(fmt=:png)
Plots.scalefontsizes(2) # makes font size bigger in plots

"""
Converts TT4 (μmol) to FT4 (μmol) using Thyrosim's internal 4th order
polynomial
"""
function FT4(TT4::Float64)
    return (0.000289 + (0.000214 * TT4) + (0.000128 * TT4^2) - (8.83e-6 *
TT4^3)) * TT4
end

"""
Converts TT4 (μmol, Thyrosim output q1) to FT4 (ng/L)
"""
function TT4_to_FT4(TT4::Float64, Vp::Float64)
    return FT4(TT4) * 777 / Vp * 1000 * 0.45
end

"""
Converts TT3 (μmol) to FT3 (ng/L = pg/mL)
"""
function TT3_to_FT3(TT4::Float64, TT3::Float64, Vp::Float64)
    return FT3(TT4, TT3) * 651 / Vp * 1000 * 0.50
end

"""
Converts TT3 (μmol) to FT3 (μmol) using Thyrosim's internal 4th order
polynomial
"""
function FT3(TT4::Float64, TT3::Float64)
    return (0.00395 + (0.00185 * TT4) + (0.000610 * TT4^2) - (0.000505 *
TT4^3)) * TT3
end


sex = false # 1 = male, 0 = female
T4dose = 0.0 # mcg
normal_TSH, normal_TT4, normal_TT3, normal_FT4, normal_FT3 = Float64[],
Float64[], Float64[], Float64[], Float64[]
skinny_TSH, skinny_TT4, skinny_TT3, skinny_FT4, skinny_FT3 = Float64[],
Float64[], Float64[], Float64[], Float64[]
obese_TSH, obese_TT4, obese_TT3, obese_FT4, obese_FT3 = Float64[],
Float64[], Float64[], Float64[], Float64[]
RTFs = [0, 0.001, 0.003, 0.005, 0.007, 0.01, 0.02, 0.05, 0.1, 0.2, 0.3,
0.4, 0.5, 0.8, 1.0]

# normal female patient
bmi = 22.5
h = 1.6
w = bmi * h^2
for rtf in RTFs
    dial = [rtf; 0.88; rtf; 0.88]
    sol = simulate(h, w, sex, days=50, dial=dial, T4dose=T4dose,
warmup=true)

    # TT4/TT3 in ug/L
    tt4 = 777.0 * sol[1, :] / sol.prob.p[47]
    tt3 = 651.0 * sol[4, :] / sol.prob.p[47]

    # FT4/FT3 (ng/L)
    ft4 = TT4_to_FT4.(sol[1, :], sol.prob.p[47])
    ft3 = TT3_to_FT3.(sol[1, :], sol[4, :], sol.prob.p[47])

    tsh = 5.6 * sol[7, :] / sol.prob.p[48]
    push!(normal_TT4, tt4[end])
    push!(normal_TT3, tt3[end])
    push!(normal_FT4, ft4[end])
    push!(normal_FT3, ft3[end])
    push!(normal_TSH, tsh[end])
end

# skinny female patient
bmi = 17
h = 1.6
w = bmi * h^2
for rtf in RTFs
    dial = [rtf; 0.88; rtf; 0.88]
    sol = simulate(h, w, sex, days=50, dial=dial, T4dose=T4dose,
warmup=true)

    # TT4/TT3 in ug/L
    tt4 = 777.0 * sol[1, :] / sol.prob.p[47]
    tt3 = 651.0 * sol[4, :] / sol.prob.p[47]

    # FT4/FT3 in ng/L
    ft4 = TT4_to_FT4.(sol[1, :], sol.prob.p[47])
    ft3 = TT3_to_FT3.(sol[1, :], sol[4, :], sol.prob.p[47])

    tsh = 5.6 * sol[7, :] / sol.prob.p[48]
    push!(skinny_TT4, tt4[end])
    push!(skinny_TT3, tt3[end])
    push!(skinny_FT4, ft4[end])
    push!(skinny_FT3, ft3[end])
    push!(skinny_TSH, tsh[end])
end

# obese female patient
bmi = 35
h = 1.6
w = bmi * h^2
for rtf in RTFs
    dial = [rtf; 0.88; rtf; 0.88]
    sol = simulate(h, w, sex, days=50, dial=dial, T4dose=T4dose,
warmup=true)

    # TT4/TT3 in ug/L
    tt4 = 777.0 * sol[1, :] / sol.prob.p[47]
    tt3 = 651.0 * sol[4, :] / sol.prob.p[47]

    # FT4/FT3 in ng/L
    ft4 = TT4_to_FT4.(sol[1, :], sol.prob.p[47])
    ft3 = TT3_to_FT3.(sol[1, :], sol[4, :], sol.prob.p[47])

    tsh = 5.6 * sol[7, :] / sol.prob.p[48]
    push!(obese_TT4, tt4[end])
    push!(obese_TT3, tt3[end])
    push!(obese_FT4, ft4[end])
    push!(obese_FT3, ft3[end])
    push!(obese_TSH, tsh[end])
end

**Comment by ksreid9** [comment]
I was playing around with the code a bit more and I think there may be an
issue with the simulate package based on the new error I was getting. When
I tried to install the package in terminal, I got an error, perhaps it does
not exist anymore for this version of Julia? Attached are the .ipynb file
with the new errors I am getting and a screenshot of the error message I
got in terminal.

Thanks,
Katarina

**Comment by biona001** [comment]
@ksreid9 I haven't looked at the issue yet. I will do so sometime next week. If you just ran the exact same code I sent, I don't think it should give an error, but in any case I'll double check on my end just to be sure.

**Comment by ksreid9** [comment]
Thanks! I did run the exact code you sent as is with no changes made. I
think there is an issue with the "simulate" package, maybe something did
not install correctly.

If it would be easier, would it be possible for you to rerun the code on
your end and instead of just running the code with BMI's 17, 22.5, and 35,
run them with the BMI's: 15, 17, 19, 21, 23, 26, 29, 32, 35, 38, 40 for
FT4, FT3, and TT3? That's really all I need from the code file.

Katarina

**Comment by biona001** [comment]
@ksreid9 The issue (I believe) is caused by numerical instability, where T3 in the brain (i.e. q8) being close to 0 is treated as a numerically negative value. 

I fixed this issue and updated package dependencies. Please try:
```julia
using Pkg
Pkg.update("Thyrosim")
```
re-run the notebook, and let me know if the issue persists.

**Comment by ksreid9** [comment]
Thanks! I reran the notebook and was able to get everything running.
However, when I rerun the notebook, the male and female outputted values
are the same which doesn't seem right. If I run each block sequentially,
then the variables should switch from female to male but the outputs
continue to be the same.
